version: '3'

services:
  api:
    container_name: rick-and-morty-api
    image: rick-and-morty-img
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3456:3456
    restart: always